# -*- coding: utf-8 -*-
"""ETLEmployees.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XmqtFQ81pn0Clurj_f9A-Jr4iw31y-7P

# Aplicação de ETL com Python
 A função desse código é pegar um CSV inicial com os dados de empregados, ver quais informações importantes está nele e tentar resumir essas informações, aplicando as rotinas de ETL.
 Aqui resumi de forma que fique os gêneros, qual o grau de graduação e soma da quantidade de pessoas desse gênero para esse grau.


# Etapa: Extract
Nas linhas abaixo serão extraídos os dados do csv que foi baixado do kaggle.
Nesse CSV tem dados de funcionários de uma empresa fictícia.
"""

import pandas as pd

df = pd.read_csv("Employee.csv")
df.head()

"""## Etapa: Transform
Verificando alguns dados que vieram como resultado. E arrumando a nova planilha

"""

df.info()

copia_employees = df.copy()

# Como não tem valores nulos, vou tirar as colunas que não quero

remover = ['JoiningYear', 'City', 'PaymentTier', 'Age', 'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot']
copia_employees = copia_employees.drop(remover, axis=1)

copia_employees.info()

# Criando outro data frame
# Inicialização dos dados que quero
employees_final = pd.DataFrame(columns=['Gênero', 'Educação', 'soma_educacao'])
employees_final['Gênero'] =['feminino', 'feminino', 'masculino', 'masculino']
employees_final['Educação'] =['Bacharelado', 'Mestrado', 'Bacharelado', 'Mestrado']
employees_final['soma_educacao'] =[0, 0, 0, 0]

for index, item in copia_employees.iterrows():
  if item['Education'] == 'Masters':
    if item['Gender'] == 'Female':
      indice = employees_final[(employees_final['Gênero'] == 'feminino') & (employees_final['Educação'] == 'Mestrado')].index[0]
      employees_final.at[indice, 'soma_educacao'] += 1
    else:
      indice = employees_final[(employees_final['Gênero'] == 'masculino') & (employees_final['Educação'] == 'Mestrado')].index[0]
      employees_final.at[indice, 'soma_educacao'] += 1
  else:
    if item['Gender'] == 'Female':
      indice = employees_final[(employees_final['Gênero'] == 'feminino') & (employees_final['Educação'] == 'Bacharelado')].index[0]
      employees_final.at[indice, 'soma_educacao'] += 1
    else:
      indice = employees_final[(employees_final['Gênero'] == 'masculino') & (employees_final['Educação'] == 'Bacharelado')].index[0]
      employees_final.at[indice, 'soma_educacao'] += 1
# Resultado:
print(employees_final)

"""## Etapa: Load
Agora que tenho os arquivos que desejo, vou passar para um CSV
"""

employees_final.to_csv('Employee_final.csv', index=False)